import type { Locale } from "@/lib/portfolio";

export type CertificateCategory = "ai-ml" | "software-cloud" | "language" | "events" | "leadership";
export type CertificateKind = "program" | "course" | "assessment" | "workshop" | "event" | "activity";

export type Certificate = {
  slug: string;
  title: string;
  issuer: string;
  issuedAt: string;
  category: CertificateCategory;
  kind: CertificateKind;
  preview: string;
  width: number;
  height: number;
  featured?: boolean;
  privacyRedacted?: boolean;
  verificationUrl?: string;
  hours?: number;
  skills?: string[];
  syllabus?: string[];
  submission?: string;
};

export const certificateCategoryLabels: Record<CertificateCategory, Record<Locale, string>> = {
  "ai-ml": { en: "AI & ML", id: "AI & ML" },
  "software-cloud": { en: "Software & Cloud", id: "Software & Cloud" },
  language: { en: "Language", id: "Bahasa" },
  events: { en: "Events", id: "Event" },
  leadership: { en: "Leadership", id: "Kepemimpinan" },
};

export const certificateKindLabels: Record<CertificateKind, Record<Locale, string>> = {
  program: { en: "Program completion", id: "Kelulusan program" },
  course: { en: "Course completion", id: "Kelulusan kelas" },
  assessment: { en: "Language assessment", id: "Asesmen bahasa" },
  workshop: { en: "Workshop", id: "Workshop" },
  event: { en: "Event attendance", id: "Kehadiran event" },
  activity: { en: "Leadership activity", id: "Aktivitas kepemimpinan" },
};

export const certificates: Certificate[] = [
  {
    slug: "coding-camp-2026-ai-engineer",
    title: "Coding Camp 2026 - AI Engineer",
    issuer: "DBS Foundation × Dicoding",
    issuedAt: "2026-07-21",
    category: "ai-ml",
    kind: "program",
    preview: "/certificates/previews/coding-camp-2026-certificate-cacc012d6y2075-1.webp",
    width: 1600,
    height: 1132,
    featured: true,
    skills: ["AI Engineering", "Machine Learning", "Deep Learning", "Generative AI", "Computer Vision", "NLP", "Model Deployment"],
    syllabus: [
      "Program akselerasi komprehensif AI Engineer oleh DBS Foundation & Dicoding",
      "Mencakup seluruh alur: Python, Machine Learning, Deep Learning Fundamental, Deep Learning Mahir, dan Generative AI"
    ],
  },
  {
    slug: "english-proficiency-test-eprt-490",
    title: "English Proficiency Test (EPrT) - Score 490 (CEFR B1)",
    issuer: "Telkom University Language Center",
    issuedAt: "2026-04-30",
    category: "language",
    kind: "assessment",
    preview: "/certificates/previews/english-proficiency-test-eprt.png",
    width: 1070,
    height: 772,
    privacyRedacted: true,
    skills: ["English Proficiency", "Listening Comprehension", "Grammar & Structure", "Reading Comprehension"],
    syllabus: [
      "Skor total 490 (setara CEFR B1) dari Telkom University Language Center",
      "Validitas pengujian: 30 April 2026 hingga 30 April 2028"
    ],
  },
  {
    slug: "english-for-business-communication-90",
    title: "English for Business Communication - Score 90%",
    issuer: "The British Institute × DBS Foundation × Dicoding",
    issuedAt: "2026-06-25",
    category: "language",
    kind: "course",
    preview: "/certificates/previews/english-for-business-communication.webp",
    width: 1191,
    height: 1684,
    privacyRedacted: true,
    skills: ["Business English", "Professional Communication", "Technical Presentation", "Email & Workplace Correspondence"],
    syllabus: [
      "Penyelesaian kursus Business English dengan nilai kelulusan 90%",
      "Diselenggarakan oleh The British Institute × DBS Foundation × Dicoding"
    ],
  },
  {
    slug: "membangun-proyek-deep-learning-tingkat-mahir",
    title: "Membangun Proyek Deep Learning Tingkat Mahir",
    issuer: "Dicoding",
    issuedAt: "2026-05-22",
    category: "ai-ml",
    kind: "course",
    preview: "/certificates/previews/membangun-proyek-deep-learning-tingkat-mahir.webp",
    width: 1600,
    height: 1132,
    featured: true,
    verificationUrl: "https://www.dicoding.com/certificates/GRX5W06E3Z0M",
    hours: 90,
    skills: ["TensorFlow", "Custom Training Loops", "Computer Vision", "NLP Transformers", "Recommender Systems", "Model Optimization"],
    syllabus: [
      "Tensor manipulation, Eager Execution, dan Graph Mode (7 jam)",
      "Custom Training Loop dan Callbacks Optimization (8 jam 10 menit)",
      "Efisiensi dan utilisasi hardware pada pelatihan model (8 jam 55 menit)",
      "Context-aware Recommender Systems (10 jam)",
      "Explainable AI dan Transformer-based NLP (13 jam)",
      "Transformer Vision Models dan Semantic Segmentation (12 jam)",
      "Deep Metric Evaluation dan Hyperparameter Analysis (15 jam)"
    ],
    submission: "Proyek time series multivariate multi-step menggunakan custom TensorFlow training loop dan model subclassing.",
  },
  {
    slug: "belajar-fundamental-deep-learning",
    title: "Belajar Fundamental Deep Learning",
    issuer: "Dicoding",
    issuedAt: "2026-05-11",
    category: "ai-ml",
    kind: "course",
    preview: "/certificates/previews/sertifikat-fundamental-deep-learning.webp",
    width: 1600,
    height: 1132,
    featured: true,
    verificationUrl: "https://www.dicoding.com/certificates/81P2OO2W8ZOY",
    hours: 110,
    skills: ["Deep Learning", "CNN", "RNN", "NLP", "Reinforcement Learning", "Model Deployment", "Multimodal"],
    syllabus: [
      "Representasi data mendalam dan arsitektur neural network (3 jam 55 menit)",
      "Library dan ekosistem Deep Learning (5 jam 25 menit)",
      "Text preprocessing, labeling, dan klasifikasi teks NLP (7 jam 10 menit)",
      "Sequence modeling dengan RNN dan LSTM (4 jam 40 menit)",
      "Evaluasi, tuning, dan regularisasi model (7 jam 30 menit)",
      "Neural Recommendation Systems (3 jam 35 menit)",
      "Reinforcement Learning (Markov Decision Process, Q-Learning) (3 jam 45 menit)",
      "Cross-platform Model Deployment dan optimasi inferensi (9 jam 35 menit)",
      "Multimodal Deep Learning (Vision & Text) (5 jam 25 menit)"
    ],
    submission: "Proyek pembangunan model deep learning klasifikasi gambar dari dataset nyata.",
  },
  {
    slug: "belajar-machine-learning-untuk-pemula",
    title: "Belajar Machine Learning untuk Pemula",
    issuer: "Dicoding",
    issuedAt: "2026-04-07",
    category: "ai-ml",
    kind: "course",
    preview: "/certificates/previews/belajar-machine-learning-untuk-pemula.webp",
    width: 1600,
    height: 1132,
    featured: true,
    verificationUrl: "https://www.dicoding.com/certificates/98XW02MN9XM3",
    hours: 90,
    skills: ["Machine Learning", "Scikit-Learn", "Supervised Learning", "Unsupervised Learning", "Feature Engineering", "Hyperparameter Tuning"],
    syllabus: [
      "Dasar-dasar dan siklus hidup Machine Learning (4 jam 20 menit)",
      "Machine Learning Workflow: pengumpulan, pembersihan, dan evaluasi data (10 jam 50 menit)",
      "Supervised Learning: Klasifikasi (KNN, Decision Tree) (6 jam 25 menit)",
      "Supervised Learning: Regresi Linear dan evaluasi metrik (5 jam 35 menit)",
      "Unsupervised Learning: K-Means Clustering (5 jam 15 menit)",
      "Strategi Feature Engineering untuk data tabular (5 jam 55 menit)",
      "Mitigasi Overfitting dan Underfitting (5 jam 35 menit)",
      "Optimasi Model dengan Hyperparameter Tuning (5 jam 10 menit)"
    ],
    submission: "Proyek pembangunan model supervised dan unsupervised learning pada dataset tabular dunia nyata.",
  },
  {
    slug: "belajar-penerapan-data-science-dengan-microsoft-fabric",
    title: "Belajar Penerapan Data Science dengan Microsoft Fabric",
    issuer: "Dicoding × Microsoft",
    issuedAt: "2026-03-14",
    category: "ai-ml",
    kind: "course",
    preview: "/certificates/previews/belajar-penerapan-data-science-dengan-microsoft-fabric.webp",
    width: 1600,
    height: 1132,
    featured: true,
    verificationUrl: "https://www.dicoding.com/certificates/KEXLQ0Q0WPG2",
    hours: 6,
    skills: ["Microsoft Fabric", "Data Science", "Data Wrangler", "MLflow", "Batch Prediction", "Enterprise Analytics"],
    syllabus: [
      "Analitik End-to-End dengan platform Microsoft Fabric (35 menit)",
      "Manajemen notebook, experiment, dan model terpadu (40 menit)",
      "Eksplorasi dan visualisasi data dengan Notebook (1 jam 20 menit)",
      "Preprocessing dan feature transformation dengan Data Wrangler (1 jam 0 menit)",
      "Pelatihan dan tracking model eksperimen dengan MLflow (55 menit)",
      "Deployment model dan eksekusi Batch Prediction terotomasi (50 menit)"
    ],
  },
  {
    slug: "membangun-aplikasi-gen-ai-dengan-microsoft-azure",
    title: "Membangun Aplikasi Gen AI dengan Microsoft Azure",
    issuer: "Dicoding × Microsoft",
    issuedAt: "2026-03-24",
    category: "ai-ml",
    kind: "course",
    preview: "/certificates/previews/dicoding-membangun-aplikasi-gen-ai.webp",
    width: 1600,
    height: 1132,
    featured: true,
    verificationUrl: "https://www.dicoding.com/certificates/NVP7N881VZR0",
  },
  {
    slug: "bring-ai-to-work-workshop",
    title: "Bring AI to Work Workshop",
    issuer: "Google Workspace",
    issuedAt: "2026-01-24",
    category: "ai-ml",
    kind: "workshop",
    preview: "/certificates/previews/bring-ai-google.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "belajar-dasar-ai",
    title: "Belajar Dasar AI",
    issuer: "Dicoding",
    issuedAt: "2026-02-18",
    category: "ai-ml",
    kind: "course",
    preview: "/certificates/previews/dicoding-belajar-dasar-ai.webp",
    width: 1600,
    height: 1132,
    verificationUrl: "https://www.dicoding.com/certificates/72ZDJE8QLZYW",
    hours: 10,
    skills: ["Artificial Intelligence", "Machine Learning Basics", "Deep Learning Overview", "Data for AI"],
    syllabus: [
      "Konsep dasar dan sejarah Artificial Intelligence (1 jam 30 menit)",
      "Peran data dan pemanfaatannya dalam ekosistem AI (1 jam 25 menit)",
      "Pengantar Machine Learning dan paradigma pembelajaran mesin (2 jam 30 menit)",
      "Pengantar Deep Learning dan studi kasus implementasi (2 jam 30 menit)"
    ],
  },
  {
    slug: "merancang-percakapan-cerdas-di-azure-ai-foundry",
    title: "Merancang Percakapan Cerdas di Azure AI Foundry",
    issuer: "Microsoft Elevate Training Center",
    issuedAt: "2026-03-06",
    category: "ai-ml",
    kind: "course",
    preview: "/certificates/previews/merancang-percakapan-cerdas-di-azure-ai-foundry.webp",
    width: 1600,
    height: 1132,
    hours: 4,
    skills: ["Azure AI Foundry", "Conversational AI", "Chat Agents", "System Prompts"],
    syllabus: [
      "Merancang conversational agent cerdas dengan Azure AI Foundry (4 jam)"
    ],
  },
  {
    slug: "offline-workshop-generative-ai",
    title: "Pengembangan Praktis Aplikasi Generative AI",
    issuer: "Microsoft Elevate Training Center",
    issuedAt: "2026-04-15",
    category: "ai-ml",
    kind: "workshop",
    preview: "/certificates/previews/offline-workshop-microsoft.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "local-generative-ai-di-browser",
    title: "Generative AI 100% Lokal di Browser",
    issuer: "Dicoding Event",
    issuedAt: "2026-03-06",
    category: "ai-ml",
    kind: "event",
    preview: "/certificates/previews/devcoach-229-gak-perlu-api-key-ini-cara-jalanin-generative-ai-100-lokal-di-browser-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "antigravity-ai-coding-partner",
    title: "Antigravity: AI Coding Partner yang Bikin Kamu Lebih Produktif",
    issuer: "Dicoding Event",
    issuedAt: "2026-04-01",
    category: "ai-ml",
    kind: "event",
    preview: "/certificates/previews/devcoach-232-antigravity-ai-coding-partner-yang-bikin-kamu-lebih-produktif-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "generate-image-tanpa-aplikasi-ai",
    title: "Gen AI: Generate Image Tanpa Aplikasi AI",
    issuer: "Dicoding Event",
    issuedAt: "2026-01-30",
    category: "ai-ml",
    kind: "event",
    preview: "/certificates/previews/dicoding-devcoach.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "idcamp-ai-web-development",
    title: "AI Web Dev: Build Real Apps with Lovable & Antigravity",
    issuer: "IDCamp × Dicoding",
    issuedAt: "2026-02-10",
    category: "ai-ml",
    kind: "event",
    preview: "/certificates/previews/id-camp-x-dicoding.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "ai-ready-career",
    title: "AI Ready Career: Mengakselerasi Peluang Karier di Era Digital",
    issuer: "METC × AICO",
    issuedAt: "2026-03-12",
    category: "ai-ml",
    kind: "event",
    preview: "/certificates/previews/metc-virtual-roadshow-x-aico-ai-ready-career-mengakselerasi-peluang-karier-di-era-digital-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "beyond-theory-proyek-ai-siap-pakai",
    title: "Beyond Theory: Membangun Proyek AI Siap Pakai",
    issuer: "Microsoft Elevate × Dicoding",
    issuedAt: "2026-04-20",
    category: "ai-ml",
    kind: "event",
    preview: "/certificates/previews/metc-x-dicoding-live-1-beyond-theory-rahasia-membangun-proyek-ai-siap-pakai-untuk-dunia-nyata-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "hackathon-dan-datathon-dengan-generative-ai",
    title: "Menjadi Pemenang Hackathon & Datathon dengan Generative AI",
    issuer: "METC × IMPHNEN × Dicoding",
    issuedAt: "2026-04-17",
    category: "ai-ml",
    kind: "event",
    preview: "/certificates/previews/virtual-roadshow-metc-x-imphnen-h2w-tips-dan-trik-menjadi-pemenang-hackathon-dan-datathon-dengan-bantuan-generative-ai-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "belajar-dasar-git-dengan-github",
    title: "Belajar Dasar Git dengan GitHub",
    issuer: "Dicoding",
    issuedAt: "2026-02-13",
    category: "software-cloud",
    kind: "course",
    preview: "/certificates/previews/dicoding-belajar-dasar-git-dengan-github.webp",
    width: 1600,
    height: 1132,
    verificationUrl: "https://www.dicoding.com/certificates/NVP7NYLDVZR0",
    hours: 15,
    skills: ["Git", "GitHub", "Version Control", "Branching & Merging", "Conflict Resolution", "Code Review"],
    syllabus: [
      "Fondasi Git dan GitHub dalam manajemen source code (1 jam 45 menit)",
      "Dasar Git: init, commit, checkout, tracking status (2 jam 5 menit)",
      "Git Branching, merging, dan penyelesaian conflict (2 jam 10 menit)",
      "Kolaborasi tim: forking, squashing commits, pull request, dan code review (2 jam 50 menit)",
      "Studi kasus manajemen repository aktif (1 jam 15 menit)",
      "Optimalisasi GitHub Profile dan Readme portofolio (1 jam 20 menit)"
    ],
  },
  {
    slug: "memulai-dasar-pemrograman",
    title: "Memulai Dasar Pemrograman untuk Menjadi Pengembang Software",
    issuer: "Dicoding",
    issuedAt: "2026-02-11",
    category: "software-cloud",
    kind: "course",
    preview: "/certificates/previews/dicoding-memulai-dasar-pemrograman-untuk-menjadi-pengembang-software.webp",
    width: 1600,
    height: 1132,
    verificationUrl: "https://www.dicoding.com/certificates/JMZVOQ413XN9",
  },
  {
    slug: "memulai-pemrograman-dengan-python",
    title: "Memulai Pemrograman dengan Python",
    issuer: "Dicoding",
    issuedAt: "2026-03-02",
    category: "software-cloud",
    kind: "course",
    preview: "/certificates/previews/dicoding-memulai-pemrograman-dengan-python.webp",
    width: 1600,
    height: 1132,
    verificationUrl: "https://www.dicoding.com/certificates/RVZK0K9DOZD5",
    hours: 60,
    skills: ["Python", "OOP", "Unit Testing", "Data Structures", "PEP8", "Algorithms"],
    syllabus: [
      "Pengenalan Python, virtual environment, dan ekosistem (5 jam 30 menit)",
      "Tipe data, ekspresi, dan manipulasi data (3 jam 55 menit)",
      "Aksi sekuensial dan implementasi algoritma (2 jam 10 menit)",
      "Control Flow: percabangan, perulangan, error handling (6 jam 20 menit)",
      "Array, Matriks, dan operasi pemrosesan data (6 jam 50 menit)",
      "Fungsi, prosedur, dan modularisasi kode (6 jam 5 menit)",
      "Object-Oriented Programming (OOP) dan pewarisan (5 jam 25 menit)",
      "Style Guide PEP8 dan konvensi penulisan kode (3 jam 35 menit)",
      "Automated Unit Testing pada Python (1 jam 35 menit)",
      "Pengenalan library populer (Data Science, ML, Web) (3 jam 20 menit)"
    ],
    submission: "Ujian evaluasi akhir komprehensif pemrograman Python.",
  },
  {
    slug: "pengenalan-logika-pemrograman",
    title: "Pengenalan ke Logika Pemrograman (Programming Logic 101)",
    issuer: "Dicoding",
    issuedAt: "2026-02-12",
    category: "software-cloud",
    kind: "course",
    preview: "/certificates/previews/dicoding-pengenalan-ke-logika-pemrograman-programming-logic-101.webp",
    width: 1600,
    height: 1132,
    verificationUrl: "https://www.dicoding.com/certificates/EYX4Q1OK6PDL",
  },
  {
    slug: "n8n-di-aws-cloud",
    title: "n8n di AWS Cloud via EasyPanel",
    issuer: "Dicoding Event",
    issuedAt: "2026-02-06",
    category: "software-cloud",
    kind: "event",
    preview: "/certificates/previews/devcoach-226-n8n.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "spotlight-pengembangan-product",
    title: "Spotlight: Pengembangan Product",
    issuer: "Dicoding Event",
    issuedAt: "2026-02-13",
    category: "software-cloud",
    kind: "event",
    preview: "/certificates/previews/devcoach-227-spotlight.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "web-is-laravel-dead",
    title: "Web: Is Laravel Dead?",
    issuer: "Dicoding Event",
    issuedAt: "2026-03-13",
    category: "software-cloud",
    kind: "event",
    preview: "/certificates/previews/devcoach-230-web-is-laravel-dead-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "devops-system-design",
    title: "DevOps: Introduction to the Art of System Design",
    issuer: "Dicoding Event",
    issuedAt: "2026-04-30",
    category: "software-cloud",
    kind: "event",
    preview: "/certificates/previews/devcoach-233-devops-code-is-not-enough-introduction-to-the-art-of-system-design-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "rethinking-the-ledger",
    title: "Rethinking the Ledger: Sistem Keuangan Immutable & Scalable",
    issuer: "Digdaya × Hackathon 2026",
    issuedAt: "2026-03-14",
    category: "software-cloud",
    kind: "event",
    preview: "/certificates/previews/digdaya-x-hackathon-2026-webinar-series-10-rethinking-the-ledger-membangun-sistem-keuangan-modern-yang-immutable-dan-scalable-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "next-gen-web-development",
    title: "Next-Gen Web Development for Performance & Accessibility",
    issuer: "Digistar Connect",
    issuedAt: "2025-03-22",
    category: "software-cloud",
    kind: "workshop",
    preview: "/certificates/previews/sertif-digistar.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "belajar-coding-dari-nol",
    title: "Belajar Coding dari Nol untuk Pemula",
    issuer: "Coding Studio",
    issuedAt: "2025-07-25",
    category: "software-cloud",
    kind: "course",
    preview: "/certificates/previews/sertif-coding-studio-code.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "intro-to-data-analyst",
    title: "Intro to Data Analyst",
    issuer: "Coding Studio",
    issuedAt: "2025-07-29",
    category: "software-cloud",
    kind: "course",
    preview: "/certificates/previews/sertif-data-analyst-coding-studio.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "belajar-excel-dari-nol",
    title: "Belajar Excel dari Nol untuk Pemula",
    issuer: "Coding Studio",
    issuedAt: "2025-07-28",
    category: "software-cloud",
    kind: "course",
    preview: "/certificates/previews/sertif-excel-coding-studio.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "fundamental-ethical-hacking-workshop",
    title: "Fundamental Ethical Hacking Workshop",
    issuer: "MBC Laboratory",
    issuedAt: "2024",
    category: "software-cloud",
    kind: "workshop",
    preview: "/certificates/previews/sertif-workshop-mbc.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "workshop-pembuatan-dan-pengelolaan-website",
    title: "Workshop Pembuatan dan Pengelolaan Website",
    issuer: "Laboratorium Sistem Komunikasi",
    issuedAt: "2024",
    category: "software-cloud",
    kind: "workshop",
    preview: "/certificates/previews/sertifikat-workshop-siskom-1.webp",
    width: 1600,
    height: 1131,
    privacyRedacted: true,
  },
  {
    slug: "digdaya-hackathon-program-overview",
    title: "Digdaya × Hackathon 2026: Program Overview & Deep Dive",
    issuer: "Digdaya × Hackathon 2026",
    issuedAt: "2026-03-10",
    category: "events",
    kind: "event",
    preview: "/certificates/previews/digdaya-x-hackathon-2026-webinar-series-5-program-overview-deep-dive-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "adaptability-growth-mindset-in-the-age-of-ai",
    title: "Adaptability & Growth Mindset in the Age of AI",
    issuer: "IDCamp Alumni Dialogue",
    issuedAt: "2026-04-01",
    category: "leadership",
    kind: "event",
    preview: "/certificates/previews/idcamp-alumni-dialogue-1-adaptability-growth-mindset-in-the-age-of-ai-certificate.webp",
    width: 1600,
    height: 1132,
  },
  {
    slug: "introduction-to-financial-literacy",
    title: "Introduction to Financial Literacy",
    issuer: "Dicoding",
    issuedAt: "2026-01-17",
    category: "leadership",
    kind: "course",
    preview: "/certificates/previews/dicoding-financial-literacy.webp",
    width: 1600,
    height: 1132,
    verificationUrl: "https://www.dicoding.com/certificates/2VX35D7M3PYQ",
  },
  {
    slug: "open-mind-2023-speaker",
    title: "Open Mind 2023: Business Opportunities for the Millennial Generation",
    issuer: "HIPMI PT Telkom",
    issuedAt: "2023-09-30",
    category: "leadership",
    kind: "activity",
    preview: "/certificates/previews/28-mohammad-raihan-hadriansyah-prasetya.webp",
    width: 1600,
    height: 1042,
    privacyRedacted: true,
  },
  {
    slug: "open-mind-2024-committee",
    title: "Open Mind 2024: Entrepreneurial Odyssey",
    issuer: "HIPMI PT Telkom",
    issuedAt: "2024-10-05",
    category: "leadership",
    kind: "activity",
    preview: "/certificates/previews/sertif-panitia-om-2024.webp",
    width: 1600,
    height: 1132,
    privacyRedacted: true,
  },
  {
    slug: "sigma-2024-ai-in-digital-society",
    title: "SIGMA 2024: AI in Digital Society Marketing Development",
    issuer: "BEM KEMA FKS Telkom University",
    issuedAt: "2024-11-02",
    category: "events",
    kind: "event",
    preview: "/certificates/previews/sertifikat-peserta-seminar-sigma-2024-mohammad-raihan-hadriansyah-prasetya.webp",
    width: 1600,
    height: 900,
    privacyRedacted: true,
  },
  {
    slug: "young-entrepreneur-camp-2024-committee",
    title: "Young Entrepreneur Camp 2024",
    issuer: "HIPMI PT Universitas Telkom",
    issuedAt: "2024-10",
    category: "leadership",
    kind: "activity",
    preview: "/certificates/previews/sertifikat-yec-2024.webp",
    width: 1600,
    height: 1131,
    privacyRedacted: true,
  },
  {
    slug: "relationship-management",
    title: "Relationship Management",
    issuer: "Telkom University",
    issuedAt: "2025-01-20",
    category: "leadership",
    kind: "course",
    preview: "/certificates/previews/sertifikat-relationship-management.webp",
    width: 1600,
    height: 1132,
    privacyRedacted: true,
  },
  {
    slug: "self-management",
    title: "Self Management",
    issuer: "Telkom University",
    issuedAt: "2025-01-21",
    category: "leadership",
    kind: "course",
    preview: "/certificates/previews/sertifikat-self-management.webp",
    width: 1600,
    height: 1132,
    privacyRedacted: true,
  },
  {
    slug: "technopreneurship",
    title: "Technopreneurship",
    issuer: "Telkom University",
    issuedAt: "2025-01-20",
    category: "leadership",
    kind: "course",
    preview: "/certificates/previews/sertifikat-technopreneurship.webp",
    width: 1600,
    height: 1132,
    privacyRedacted: true,
  },
];
